CREATE TABLE `cambrano_radar`.`casillas_votos_2024` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `id_seccion_ine` int(11) DEFAULT NULL,
  `clave_seccion_ine` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_tipo_casilla` int(11) DEFAULT NULL,
  `clave` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `votos_nulos` int(11) DEFAULT NULL,
  `votos_can_nreg` int(11) DEFAULT NULL,
  `lista_nominal` int(11) DEFAULT NULL,
  `status` varchar(120) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `codigo_plataforma` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `referencia_importacion` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fechaR` datetime DEFAULT NULL,
  `id_distrito_local` int(11) DEFAULT NULL,
  `clave_distrito_local` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_distrito_federal` int(11) DEFAULT NULL,
  `clave_distrito_federal` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `calle` text COLLATE utf8mb4_unicode_ci,
  `colonia` text COLLATE utf8mb4_unicode_ci,
  `id_localidad` text COLLATE utf8mb4_unicode_ci,
  `clave_localidad` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_estado` int(11) DEFAULT NULL,
  `id_municipio` int(11) DEFAULT NULL,
  `clave_municipio` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo` int(11) DEFAULT NULL COMMENT '0-municipio // 1- distrito local // 2- distrito federal',
  `id_pais` int(11) DEFAULT NULL,
  `codigo_postal` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `longitud` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `latitud` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `id_cuartel` int(11) DEFAULT NULL,
  `num_int` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `num_ext` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `referencia` varchar(250) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo_seccion` varchar(45) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `clave_UNIQUE` (`clave`,`codigo_plataforma`),
  KEY `casillas_votos_2024_id_tipo_casilla_idx` (`id_tipo_casilla`),
  KEY `casillas_votos_2024_id_seccion_ine_idx` (`id_seccion_ine`),
  KEY `casillas_votos_2024_id_distrito_federal_idx` (`id_distrito_federal`),
  KEY `casillas_votos_2024_id_distrito_local_idx` (`id_distrito_local`),
  KEY `casillas_votos_2024_id_cuartel_idx` (`id_cuartel`),
  KEY `casillas_votos_2024_tipo` (`tipo`),
  CONSTRAINT `casillas_votos_2024_id_cuartel` FOREIGN KEY (`id_cuartel`) REFERENCES `cuarteles` (`id`),
  CONSTRAINT `casillas_votos_2024_id_distrito_federal` FOREIGN KEY (`id_distrito_federal`) REFERENCES `distritos_federales` (`id`),
  CONSTRAINT `casillas_votos_2024_id_distrito_local` FOREIGN KEY (`id_distrito_local`) REFERENCES `distritos_locales` (`id`),
  CONSTRAINT `casillas_votos_2024_id_seccion_ine` FOREIGN KEY (`id_seccion_ine`) REFERENCES `secciones_ine` (`id`),
  CONSTRAINT `casillas_votos_2024_id_tipo_casilla` FOREIGN KEY (`id_tipo_casilla`) REFERENCES `tipos_casillas` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4837 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Casillas votos';

